project: 
  type: website
  
website: 
  page-navigation: true
  title: "Studiereis Dairyconsult" 
  site-url: "https://albartcoster.github.io/studiereis_cordoba/" 
  repo-url: https://github.com/albartcoster/studiereis_cordoba
  repo-actions: [edit] ## ,issue3
  
  page-footer:
    right: "Pagina gemaakt met plezier en met [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Albart Coster, 2023"
    
  sidebar:
    logo: "images/DC.webp"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://albartcoster.github.io/studiereis_cordoba
        text: "Dairyconsult.nl"
      - icon: github
        href: https://github.com/albartcoster/studiereis_cordoba
        text: "Studiereis"

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welkom
      - href: cordoba.qmd
        text: Info over gebied
      - href: planning.qmd
        text: Planning van de reis
      - href: deelnemers/deelnemers.qmd
        text: Deelnemerslijst
      
      #- section: quarto-workflows/index.qmd
      #  contents: 
      #    - quarto-workflows/browser.md
      #    - quarto-workflows/rstudio.qmd
      #    - quarto-workflows/jupyter.md 
      #- learning-more.qmd
      #- href: transition-from-rmarkdown.qmd
      #  text: Planning van de reis


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    email-obfuscation: references
    link-external-icon: false


filters:
  - include-files.lua
  - quarto

  
