---
title: "Informatie over gebied"
---

## Córdoba {#cordoba}

Córdoba is een stad in Andalusië in het zuiden van Spanje. Het is de hoofdstad van de provincie Córdoba. De stad ligt op 122 meter boven zeeniveau, aan de rivier de Guadalquivir en aan de voet van het gebergte Sierra Morena. In 2005 had ze 321.165 inwoners, waarmee het de derde stad van Andalusië is. Het is de warmste stad van Europa: de temperatuur stijgt elk jaar weer geregeld boven de 35 °C.

Córdoba was ooit een van de belangrijkste steden ter wereld, in de 10de eeuw zelfs de op een na grootste, met een voor die tijd ongekend hoog inwonertal van rond de 500.000. Het was de hoofdstad van het middeleeuwse emiraat Córdoba, later het kalifaat Córdoba. Uit die tijd zijn talrijke monumenten overgebleven, waarvan de Mezquita het bekendste is. Sinds 1984 staat het historische centrum van de stad op de Werelderfgoedlijst van UNESCO.

De stad is de geboorteplaats van filosofen als Seneca, Averroes en Maimonides. In culinaire kringen is Córdoba bekend vanwege het gerecht Rabo de Toro, een stoofpot van stierenstaart.

Als gevolg van de Spaanse kolonisaties dragen op het Amerikaanse continent meer dan 1000 plaatsen de naam Córdoba. De belangrijkste daarvan is Córdoba in Argentinië. 

## Landbouw in Andalusie {#landbouw}