---
title: "Plánning y contacto"
---

# Plánning {#planning}

## 13-11
| Tiempo | Lugar |  |
| --- | --- | --- |
| 9:50 | Schiphol | Salido vuelo KL 1701 de NL |
| 11:45 | Berlin Schönefeld | Salido vuelo I23677 de DE | 
| 12:00 | Madrid Barajas | Llegada vuelo KL 1701 |
| 13:00 | Córdoba | Llegada gente Catalunya | 
| 14:30 | Madrid Plaza de Atocha | Salida AVE Plaza de Atocha a Córdoba | 
| 15:00 | Madrid Barajas | Llegada vuelo I23677 de DE |
| 16:30 | Córdoba | Llegada gente de NL | 
| 17:00 | Madrid Plaza de Atocha | Salida con AVE a Córdoba | 
| 19:00 | Córdoba | Llegada gente de DE | 
| 21:00 | Córdoba, Hotel Conquistador | Cena y introducción |


## 14-11
| Tiempo | Lugar |  |
| --- | --- | --- |
| 7:30 | Hotel Conquistador | Desayono |
| 8:30 | Hotel Conquistador | Salida con autocar a COVAP|
| 9:30 | COVAP | Llegada a COVAP |
| 9:30 - 13:30 | Visita COVAP | 
| 13:30 | COVAP| Comida |
| 15:00 | Granja Noriega | Granja vacuno y porcino iberico|
| 18:00 | Hotel Conquistador | Vuelta |
| 19:00 | Córdoba | Visita guiada por Córdoba, por Berend Coster |
| 20:00 + | Córdoba | Programa libre |

## 15-11
| Tiempo | Lugar |  |
| --- | --- | --- |
| 7:30 | Hotel Conquistador | Desayono | 
| 9:00 | Hotel Conquistador | Salida con bus |
| 10:00 | Ganadería Jesus López | [Granja lechera](https://maps.app.goo.gl/XZL4FxoajgX6ZTjm7) |
|11:30 | Hermanos Pizarro | [Granja lechera](https://maps.app.goo.gl/6zpwsDxNax8G8XWo9) |
|14:15 | Pozoblanco | Comida |
|16:00 | Torronteras | Visita a granja lechera |
| 19:00 | Córdoba | Cena en Córdoba | 

## 16-11
| Tiempo | Lugar |  |
| --- | --- | --- |
| 7:00 + | Hotel Conquistador | Desayuno |
| 9:00| Estación Córdoba|  Salida gente NL | 
| 10:00|Estación Córdoba|  Salida gente DE |
| 13:30 | Madrid Barajas | Salida vuelo KL1702 a NL |
| 15:40 | Schiphol | Llegada vuelo KL1702 NL |
| 15:55 | Madrid Barajas | Salida vuelo I23672 a Berlin Schönefeld | 
| 19:00 | Berlin Schönefeld | Llegada  Berlin |


# Contacto {#cgegevens}

|  |  |  |
|--|---|---|
|Iu Salvador|<iu@dairyconsult.nl> | +34 670319309 | 
|Jaap van Zwieten | <jaap@dairyconsult.nl> | +31 626426483 |
|Albart Coster | <albart@dairyconsult.nl> | +31.642402923 | 
|Hotel Conquistador| [www.eurostarshotels.nl/eurostars-conquistador.html](https://www.eurostarshotels.nl/eurostars-conquistador.html) | +34 957481102 | 
|Autocares Alcántara | [www.autocaresalcantara.com](https://www.autocaresalcantara.com) | +34 957 429 130 |
